# Generated by Django 4.2.1 on 2023-05-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('sale_date', models.DateField()),
                ('payment_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('FO', 'Food'), ('BG', 'Beverages'), ('CG', 'Ciggaretes'), ('ND', 'No Data')], default='ND', max_length=4),
        ),
    ]
