# Generated by Django 4.2.1 on 2023-05-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_invoice_buyer_invoice_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='buyer',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='seller',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='sale_date',
            new_name='sales_date',
        ),
        migrations.AddField(
            model_name='invoice',
            name='material',
            field=models.ManyToManyField(to='app.material'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('INVOICE', 'Invoice'), ('PROFORMA', 'Proforma invoice')], default='INVOICE', max_length=20, verbose_name='status'),
        ),
    ]
