# Generated by Django 4.2.1 on 2023-06-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_company_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK TRANSFER', 'Bank transfer')], default='CASH', max_length=20, verbose_name='payment_method'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('INVOICE', 'Invoice'), ('PROFORMA', 'Proforma invoice')], default='INVOICE', max_length=20, verbose_name='type'),
        ),
    ]
