# Generated by Django 4.2.1 on 2023-06-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_invoice_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='price',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
