# Generated by Django 4.2.1 on 2023-06-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_material_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
