# Generated by Django 4.2.1 on 2023-06-03 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_material_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='quantity',
        ),
        migrations.CreateModel(
            name='OrderMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.material')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='orderedmaterial',
            field=models.ManyToManyField(to='app.ordermaterial'),
        ),
    ]
