# Generated by Django 4.2.1 on 2023-06-03 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_order_remove_invoice_orderedmaterial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.material'),
            preserve_default=False,
        ),
    ]
