# Generated by Django 4.2.1 on 2023-06-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_order_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='material',
        ),
        migrations.AddField(
            model_name='order',
            name='material',
            field=models.ManyToManyField(to='app.material'),
        ),
    ]
