# Generated by Django 4.2.1 on 2023-06-03 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_order_material_order_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='material',
        ),
        migrations.AddField(
            model_name='order',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.material'),
        ),
    ]
