# Generated by Django 4.2.1 on 2023-06-03 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_order_material_order_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='material',
        ),
    ]
