# Generated by Django 4.2.1 on 2023-06-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_order_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='vat_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=38),
        ),
    ]
